### ISSUE TITLE
Double line on navigation

### ISSUE THREAD

**Issue by carlaberkers** [canonical-webteam/practices#101]
Great work on the site! Small piece of design feeback:
![screen shot 2018-11-20 at 15 56 38](https://user-images.githubusercontent.com/7945048/48785590-edb7b500-ecdc-11e8-8458-e43f9cb5576f.png)

On Chrome 70.0.3538.102 on desktop, the line underneith the "home" and "Github repo" menu items seems to be two pixels high, where the rest of the navigation is normal.

**Comment by bartaz** [comment]
Thanks @carlaberkers. This should already by fixed by #99. Do you still see it after refreshing the site?

**Comment by nottrobin** [comment]
@carlaberkers I believe this is fixed as @bartaz mentioned, so I'm closing it. Please re-open if I'm mistaken.
