### ISSUE TITLE
Add `is-active` class to active link in sidebar nav

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-webteam/practices#115]
The styles are already in styles.css so just need to add `is-active` to the relevant anchor

![screenshot_2](https://user-images.githubusercontent.com/25733845/48843929-74799a00-ed90-11e8-86f2-6b764c36b580.png)

**Comment by nottrobin** [comment]
Fixed in https://github.com/canonical-webteam/practices/pull/116
