### ISSUE TITLE
Header does not fit on small screens

### ISSUE THREAD

**Issue by anthonydillon** [canonical-webteam/practices#117]
The header is to large on small screens. Maybe lose the text at a breakpoint?

![screenshot_20181121-200528__01](https://user-images.githubusercontent.com/1413534/48865926-f4bbf180-edc8-11e8-9650-4999488ffda3.jpg)

**Comment by anthonydillon** [comment]
I was suggesting we `display: none` the text element in the SVG when it hits a breakpoint. Do you think this would work?

**Comment by nottrobin** [comment]
@anthonydillon I did understand your suggestion, but I think leaving the header the same is preferable to hiding or changing it. Which is why I was asking what you think of "Web and design practices". "Web and design team practices" is a bit of a mouthful anyway.
