### ISSUE TITLE
Merge react.md into a generic document about JavaScript guidelines

### ISSUE THREAD

**Issue by nottrobin** [canonical-webteam/practices#118]
Rationale here: https://github.com/canonical-webteam/practices/pull/106#discussion_r235654424

> actually most of the recommendations in this document should be generalised as JavaScript guidelines - naming of component files and JSX files should probably sit alongside general advice for naming JavaScript files, that advice and advice on Redux could also be applicable in non-React apps. So what should probably happen is that any React-specific advice should form a section in a general document on JavaScript advice.

**Comment by squidsoup** [comment]
+1, `code-formatting.md` should also be merged.

**Comment by squidsoup** [comment]
Fixed in https://github.com/canonical-webteam/practices/pull/123
