### ISSUE TITLE
Code-Formatting Page JS heavy

### ISSUE THREAD

**Issue by b-m-f** [canonical-webteam/practices#119]
[https://canonical-webteam.github.io/practices/coding/code-formatting](https://canonical-webteam.github.io/practices/coding/code-formatting) seems very focussed on **JavaScript**. 
Should we move the first sentence:
```
To ensure consistency across our codebases, we utilise Prettier.
```
into the **JavaScript** block?

How about keeping Code-Formatting rules in the respective language documents => Maybe quicker to find the info for the language I am looking up?

**Comment by nottrobin** [comment]
Yes I think these should be broken down by language, that's probably a more useful grouping.

**Comment by squidsoup** [comment]
Fixed in https://github.com/canonical-webteam/practices/pull/123
