### ISSUE TITLE
Typo text "closeing" instead of "closing" 

### ISSUE THREAD

**Issue by lzaaldian** [canonical-webteam/practices#140]
Hello, I think I found a typo on HTML Code Standard page in General Rules list. It is typed as closeing instead of closing. Here's the image to show where the typo is

<img width="1498" alt="jepretan layar 2018-12-11 pukul 9 12 33 pm" src="https://user-images.githubusercontent.com/3760093/49806286-ed658380-fd89-11e8-93e7-89b976068c12.png">

**Comment by nottrobin** [comment]
Yep! Thanks so much. That's probably @anthonydillon's fault 😜. I'll fix it when I get a chance, or if you get a chance that'd be awesome 🙂

**Comment by lzaaldian** [comment]
I'd like to try 👨🏻‍💻. I will create a pull request soon
