### ISSUE TITLE
Typo text "uneffected" instead of "unaffected"

### ISSUE THREAD

**Issue by lzaaldian** [canonical-webteam/practices#142]
Hello, I think I found a typo on Stylesheet Code Standard page in State Classes section. It is typed as 
"uneffected" instead of "unaffected". Here's the image to show where the typo is

<img width="1498" alt="jepretan layar 2018-12-11 pukul 10 14 13 pm" src="https://user-images.githubusercontent.com/3760093/49846227-dad86200-fdfc-11e8-9413-54da678e36c8.png">

**Comment by nottrobin** [comment]
@lzaaldian thanks so much for all this effort. In future, for things like typos or small suggestions, feel free to simply file the PR without creating an issue. Unless you really want to create the issue for some reason.

**Comment by lzaaldian** [comment]
Understood 🙆🏻‍♂️. Thank you for your guidance. I'll do better next time

**Comment by nottrobin** [comment]
Heh. It wasn't a criticism - what you're doing is very thorough. Just trying to save you time =)
