### ISSUE TITLE
Broken link on Canonical Web team's GitHub profile

### ISSUE THREAD

**Issue by lzaaldian** [canonical-webteam/practices#146]
Pardon me, I don't know where to report this issue to, therefore I create this issue here. So, here's what I found.

The link on Canonical Web team's GitHub profile is broken. It's redirected to a page which show 404 message. Here's the image to explain what I mean

<img width="1498" alt="jepretan layar 2018-12-13 pukul 11 45 04 am" src="https://user-images.githubusercontent.com/3760093/49918354-6d4c3480-fed5-11e8-9bba-9cd711b9d1c2.png">

Here's the page the link redirected to

<img width="1498" alt="jepretan layar 2018-12-13 pukul 11 46 34 am" src="https://user-images.githubusercontent.com/3760093/49918387-8e148a00-fed5-11e8-9277-ae663db8d94c.png">

**Comment by barrymcgee** [comment]
Thanks for flagging this @lzaaldian, I've now updated the link to our [Canoncial Web and design practices](https://canonical-webteam.github.io/practices/) site.
