### ISSUE TITLE
State the license of the source code in this repository

### ISSUE THREAD

**Issue by destan** [canonical-webteam/practices#161]
What is the license of the source code (of the web page) in this repository. We'd like to for it and change it according to our company's needs if the license allows it.

**Comment by nottrobin** [comment]
Good point, thanks @destan. We generally license our team's code as [LGPLv3](https://opensource.org/licenses/lgpl-3.0.html), so I've filed a PR to add that to this repo.

But we like to be fairly liberal with our work - feel free to ask us if you want to use this in a way that the license technically prohibits.

**Comment by pmahnke** [comment]
@nottrobin I think we do 

> ## License
> 
> The content of this project is licensed under the Creative Commons Attribution-ShareAlike 4.0 International license, and the underlying code used to format and display that content is licensed under the LGPLv3 by Canonical Ltd.
> 
> With ♥ from Canonical
