### ISSUE TITLE
Document how to create a design spec

### ISSUE THREAD

**Issue by anthonydillon** [canonical-webteam/practices#28]
We need to create a document which details how to create a design spec.

https://github.com/vanilla-framework/vanilla-framework/issues/1113

**Comment by MariaVrachni** [comment]
I use a design spec template provided by Carla when I first joined. Here is a link:

[https://docs.google.com/a/canonical.com/document/d/1FB1VJxspH0nrcfpJr_7G-hA0BjasfJgrvy2S8-Jk69I/edit?usp=sharing](url)
