### ISSUE TITLE
We should use the HTML data attribute to target elements using JS

### ISSUE THREAD

**Issue by barrymcgee** [canonical-webteam/practices#31]
This approach means that we have clean separation between attributes used for JS interaction and attributes used for styling.

Supporting:
- https://toddmotto.com/data-js-selectors-enhancing-html5-development-by-separating-css-from-javascript/
- https://emilien.klein.st/posts/using-data-hook-attribute/

Note:
- There is a slight performance penalty for using data attribute selectors but, even for a very high number of selections, this is negligible in absolute terms: https://decadecity.net/blog/2013/07/04/using-data-selectors-for-javascript-functionality

**Comment by nottrobin** [comment]
I wholeheartedly agree with this. And I think it should impact the work done in https://github.com/vanilla-framework/vanilla-framework/pull/1264.

@barrymcgee I would be delighted if you would throw together a quick best practice document to mention this.

**Comment by anthonydillon** [comment]
Please update the current practice so that can be reviewed.

**Comment by Caleb-Ellis** [comment]
Closing as this issue has been addressed in the [JS coding practices](https://github.com/canonical-webteam/practices/blob/master/coding/js.md).
