### ISSUE TITLE
Create a shared repo where we can add cards for all squad retrospective actions

### ISSUE THREAD

**Issue by MariaVrachni** [canonical-webteam/practices#36]
## Summary

Currently each team has their own way of documenting their retrospective actions. Retro actions may involve across-squad collaboration, which will be promoted if the actions are visible to all teams.

**Comment by nottrobin** [comment]
Interesting idea. @anthonydillon did you create a admin org? This could be a repo on that org.

**Comment by anthonydillon** [comment]
Thanks @MariaVrachni, have you considered documenting your retros in the meeting notes repo? Then creating cards for each person in there respective projects. If the action is general then it could be filled under the squad repo.

**Comment by MariaVrachni** [comment]
Thanks @anthonydillon This is also a good idea. I was thinking each squad's retro would be more transparent if the actions were gathered in one place. Lets try the squad board for now. Closing this issue.
