### ISSUE TITLE
Meetings: pre-planning

### ISSUE THREAD

**Issue by kasiag** [canonical-webteam/practices#52]
Pre-planning, or in other words backlog gardening meeting, is a frequent squad meeting to organise, prioritise and clarify their backlog items. The objective of that meeting is to regularly organise the work in preparation for a sprint management meeting and sprint itself, improve knowledge of requirements and identify blockers.

Pre-planning meeting happens regularly each week, includes all members of the squad and lasts between 1-1.5h

What to do at a pre-planning meeting:
1. prioritise existing backlog items, if not possible due to insufficient knowledge: 
2. take your time to understand each backlog item, read the brief, an epic or even a spec
3. think if all requirements of the backlog item are clear, do you need to ask for more information? 
4. if a backlog item doesn't have a brief and it should, request it from stakeholders
5.if a backlog item doesn't have an epic, create one with a title, description and link it to the backlog spreadsheet
6. check for new work requests e.g emails from stakeholders, new briefs coming in, bug requests,  add them to the backlog and follow steps 1-5

Sometimes the team will be able to do steps 1-6 early in the process, other times it might take couple of pre-planning meetings to gather all required information hence the regularity of this meeting and a need to be proactive in gathering requirements.

Depending on a stage of an iteration the squad is in, it will introduce additional steps to the pre-planning. The week before next iteration (which is week 2 in scrum cycle): 
7. the squad should identify the amount of points and list of deliverables they are willing to commit to in the next iteration
8. once the proposed for next iteration backlog items have been clarified and briefs/epics are done then they are ready to be split into tasks and estimated

Tips from the PM:

- when planning you next sprint deliverables consider any upcoming holidays, public holidays or in general out of office time
- if you need help with following the format or fitting into allocated time ask your PM to come into the meeting and facilitate
- if you're having trouble with gathering the requirements or clearing blockers escalate that to your PM

**Comment by Caleb-Ellis** [comment]
Action: Add pre-planning doc to practices
