### ISSUE TITLE
Team Off-Site Meeting 12/12/2017 - Notes & Actions

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-webteam/practices#58]
On the 12th of December 2017, the team held an off-site meeting at the Ace Hotel in Shoreditch to discuss the process, strategy, and to have a bit of fun. We first voted on the topic we wanted to talk about, and then chose the 4 most popular topics and held retros. The topics were: Using evidence to improve our websites, MVP thinking, Design threads, and Pastoral care

The notes from the off-site have been included below, with the important actions in **bold.** 

# Retro 1 - Using evidence to improve our websites

## User Testing

- The team discussed whether it would be feasible to do testing before big decisions were made. A potential solution would be to create low-fi prototypes and test those. 

- The team agreed that stakeholders need to know about the purpose and value of any tests we run, including the end goals, metrics, etc.

- **The team raised a concern that finding valid users for testing purposes was hard because of our very niche products. The team explored the use of hallway testing - building relationships with customers/community while at events & conferences. By doing this, we can find the right people, build a database of valid testers, and remote test our products with them.**

- **The team thought that currently stakeholders do not understand the value of qualitative data, and are only concerned with quantitative data.  We need to show stakeholders the quantitative data (e.g. from AB tests), and then use this data to explain and justify running more detailed tests that would result in qualitative data.**

## Dashboard

- The team thought that it would be beneficial to look at analytics through Dashboard in order to check page views, download numbers, etc.

- Squads need to use Dashboard to define KPI’s

- **Each Squad should have a meeting about KPI’s and dashboard.** 

## AB Testing
- We need to define meaningful goals for AB tests

- We need to define the expected user journeys

- We need to then validate these user journeys against analytics gathered from AB tests

## Site Build

- Ensure GA actions and events are implemented on anything that is worth measuring

- The team identified that there is a trade-off between site performance & GA events, therefore events should be on elements that we definitely need and want to track. 

- **Squads will have a meeting about GA events - what UX’ers want to track**

- **The team identified that the site speed varies greatly worldwide, for e.g. it is slow to load in places like China & India. The developers will have a meeting to discuss worldwide site performance & speed**

## Extra thoughts

- We need to be careful of what we “target” and consider a “metric”, as it might have a negative effect on the overall experience.

# Retro 2 - MVP Thinking

## Planning

- We need to measure the success of MVP’s or “phases” by testing them and analysing the data

- **The squads need to define what is the most “viable” product. An idea is to define this in the planning meetings while discussing the work.**

- **The team wants more mini sprints for certain epics. In planning, we should look at features and decide what the best way to tackle it is: within the 2-week iteration or a mini sprint**

## MVP / Future Vision

- **The team wanted more one-day “future design” workshops/sprints to find out the bigger picture, and to also identify the MVP’s, and use this information to communicate with engineers**

## MVP as a research tool

- We need to tie MVP’s into testing

- The team discussed that we need to improve our communication with stakeholders about what is the MVP, and then show them the longer plan too

- **The team identified that when an MVP is developed, it is a good time to do user testing**

## MVP in Demo’s

- **The team discussed that we should utilise testing data when we are presenting work at the demo meeting. For example, if we are showing a version B of a homepage, we should show the data of the A/B test to discuss which version is better.**

# Retro 3 - Design Threads

## GitHub “Team Discussions”

**(You have to be a part of a “team” to access the GitHub team discussions)**

- A stickied post can contain a link to the spec, as well as a refined summary of the discussions, had in the forum thread

- Members of the discussions forum can link to specific cards when discussing topics

- **A lot of the team were keen to keep design threads on Git. “Github Team Discussions”, a new forum-like feature on GitHub, was proposed, and the squads have agreed to try it. Find out more here:** https://github.com/blog/2471-introducing-team-discussions

## Proposed rules for team discussions

- It should be easy to see finished and agreed designs

- Should be open to the community 

- The history should be preserved 

- It must email (alert) people 

# Retro 4 - Pastoral Care

- The company needs to be more transparent on things like training & team budgets

- More healthy snacks in the kitchen (not just fruit!)

- Daily yoga meetup 

- More structured fun (pub of the week, etc.)

**Comment by anthonydillon** [comment]
@shivjoshi1996 thanks, can you move this issue to our [meeting notes repo](https://github.com/ubuntudesign/meeting-notes/), please.

**Comment by shivjoshi1996** [comment]
@anthonydillon Moved here, cheers: https://github.com/ubuntudesign/meeting-notes/issues/209

**Comment by anthonydillon** [comment]
@shivjoshi1996 cheers
